# Assignment-01

In [1]:
import numpy as np

## 01 print()

In [4]:
print("my name is muneeb")

my name is muneeb


## 02 array()

In [5]:
a= np.array([0,10,15,20,25,30])
print(a)

[ 0 10 15 20 25 30]


## 03 arange()

In [6]:
a= np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


## o4 reshape()

In [7]:
a= np.arange(10).reshape(5,2)
print(a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


## 05 add()

In [9]:
a= np.arange(1,6)
b= np.arange(11,16)
print(a)
print(b)
c= np.add(a,b)
print(c)

[1 2 3 4 5]
[11 12 13 14 15]
[12 14 16 18 20]


## 06 subtract()

In [10]:
c= np.subtract(b,a)
print(c)

[10 10 10 10 10]


## 07 divide()

In [11]:
c= np.divide(a,b)
print(c)

[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333]


## 08 multiply()

In [12]:
c= np.multiply(b,a)
print(c)

[11 24 39 56 75]


## 09 mod()

In [13]:
c= np.mod(a,b)
print(c)

[1 2 3 4 5]


## 10 divmod()

In [14]:
c= np.divmod(a,b)
print(c)

(array([0, 0, 0, 0, 0], dtype=int32), array([1, 2, 3, 4, 5], dtype=int32))


## 11 power()

In [15]:
c= np.power(b,a)
print(c)

[    11    144   2197  38416 759375]


## 12 asfarray()

In [16]:
c= np.asfarray(a)
print(c)

[1. 2. 3. 4. 5.]


## 13 around()

In [19]:
x= np.array([12.345,34.567,45.123])
y= np.around(x)
print(y)

[12. 35. 45.]


## 14 floor()

In [18]:
y= np.floor(x)
print(y)

[12. 34. 45.]


## 15 ceil()

In [20]:
y= np.ceil(x)
print(y)

[13. 35. 46.]


## 16 random.rand()

In [23]:
y= np.random.rand(35)
print(y)

[0.03992487 0.89593387 0.85853572 0.80240268 0.29745287 0.17478535
 0.21092746 0.84643958 0.04323427 0.97414836 0.99107189 0.38206346
 0.0938547  0.38792709 0.78852131 0.62969705 0.19812685 0.85544132
 0.29311716 0.51776104 0.11716659 0.2627983  0.83715549 0.25538701
 0.38019897 0.96528305 0.38938457 0.2111896  0.25961884 0.61792207
 0.06878622 0.17628687 0.82104151 0.10214774 0.76222267]


## 17 random.randint()

In [24]:
y= np.random.randint(45)
print(y)

12


## 18 sort()

In [28]:
x= np.array([10,23,5,8,20])
y= np.sort(x)
print(y)

[ 5  8 10 20 23]


## 19 slicing()

In [30]:
print(y[1:4])

[ 8 10 20]


## 20 array_split()

In [32]:
z= np.array_split(x,3)
print(z)

[array([10, 23]), array([5, 8]), array([20])]


## 21 flip()

In [33]:
z= np.flip(x)
print(z)

[20  8  5 23 10]


## 22 unique()

In [34]:
x= np.array([2,5,7,4,8,10,6,23,4,5,2,4,8,10])
y= np.unique(x)
print(y)

[ 2  4  5  6  7  8 10 23]
